apiVersion: v1
kind: Service
metadata:
  name: mlops-model-service
spec:
  type: NodePort
  selector:
    app: mlops-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
